// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnzPwLyCp3CVXKtTPWx2EpKJZ6H0Y0k9s',
    appId: '1:798641031885:web:1e6b8cad9cf2633c293784',
    messagingSenderId: '798641031885',
    projectId: 'hocflutter2024-80ea4',
    authDomain: 'hocflutter2024-80ea4.firebaseapp.com',
    storageBucket: 'hocflutter2024-80ea4.appspot.com',
    measurementId: 'G-CJ7Q7NY2Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh-o3QNddYKc313i6LOdlw5Zbu0Ntc3dM',
    appId: '1:798641031885:android:0b7ec4f184b8263f293784',
    messagingSenderId: '798641031885',
    projectId: 'hocflutter2024-80ea4',
    storageBucket: 'hocflutter2024-80ea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkL1FlHI8d1HbFhArRxNBcKgUGKYjHXFs',
    appId: '1:798641031885:ios:17914560502f2103293784',
    messagingSenderId: '798641031885',
    projectId: 'hocflutter2024-80ea4',
    storageBucket: 'hocflutter2024-80ea4.appspot.com',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkL1FlHI8d1HbFhArRxNBcKgUGKYjHXFs',
    appId: '1:798641031885:ios:17914560502f2103293784',
    messagingSenderId: '798641031885',
    projectId: 'hocflutter2024-80ea4',
    storageBucket: 'hocflutter2024-80ea4.appspot.com',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnzPwLyCp3CVXKtTPWx2EpKJZ6H0Y0k9s',
    appId: '1:798641031885:web:1bfff8c8908b7726293784',
    messagingSenderId: '798641031885',
    projectId: 'hocflutter2024-80ea4',
    authDomain: 'hocflutter2024-80ea4.firebaseapp.com',
    storageBucket: 'hocflutter2024-80ea4.appspot.com',
    measurementId: 'G-C11CD0YZ8L',
  );
}
